name: Docker Image CI

on:
  push:
    branches:
      - main
      - develop
      - release/*   # Додатково можна враховувати гілки для релізів

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine Docker tag
      id: determine-tag
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
          echo "tag=develop" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
          VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/release\///')
          echo "tag=$VERSION" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ub1_helper:${{ steps.determine-tag.outputs.tag }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ub1_helper:volume
        cache-to: type=inline

    - name: Post job cleanup
      if: always()
      run: docker logout
